swagger: '2.0'
info:
  version: 1.0.0
  title: Fake Login Page
  description: >
    This API demonstrates a fake login page designed as a proof of concept (POC) for capturing credentials.  
    **Note:** This is for educational purposes only. Do not misuse it.
paths:
  /:
    post:
      summary: Fake login endpoint
      description: This endpoint captures login credentials submitted via the form.
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: username
          in: formData
          required: true
          type: string
          description: The username entered in the fake login form.
        - name: password
          in: formData
          required: true
          type: string
          description: The password entered in the fake login form.
      responses:
        '200':
          description: Login successful
        '400':
          description: Bad request - invalid input
host: vinothpentest.free.beeceptor.com
basePath: /api/v1
schemes:
  - https
