swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    Documentation for the Classic API.

paths:
  /signin:
    post:
      parameters:
        - name: Email
          in: formData
          required: true
          type: string
        - name: password
          in: formData
          required: true
          type: string
        - name: token
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: Success Request
      tags:
        - signin
      operationId: Signin
      summary: |
        <h1>Random Test Value</h1><marquee>Scrolling Text</marquee>
